const API="http://127.0.0.1:8000";
const messages=document.getElementById("messages"),form=document.getElementById("composer"),prompt=document.getElementById("prompt"),status=document.getElementById("status"),chatList=document.getElementById("chatList"),fileInput=document.getElementById("fileInput"),fileBar=document.getElementById("fileBar");
let cid=localStorage.getItem("jarvisCid")||crypto.randomUUID(),files=[],voiceOn=false;localStorage.setItem("jarvisCid",cid);
function welcome(){messages.innerHTML='<div class="welcome"><div class="orb">J</div><h1>How can I help?</h1><p>Chat, code, search, upload files, or talk to JARVIS.</p><div class="cards"><button data-prompt="Explain how artificial intelligence works">🧠 Explain AI</button><button data-prompt="Write a Python program for a number guessing game">💻 Write code</button><button data-prompt="Search the web for the latest technology news">🔎 Web search</button></div></div>'}
function add(role,text){document.querySelector(".welcome")?.remove();const row=document.createElement("div");row.className="msg "+role;row.innerHTML='<div class="avatar">'+(role==="user"?"U":"J")+'</div><div class="bubble"></div>';row.querySelector(".bubble").textContent=text;messages.appendChild(row);messages.scrollTop=messages.scrollHeight;return row.querySelector(".bubble")}
async function history(){try{const r=await fetch(API+"/history/"+cid),d=await r.json();if(d.messages?.length){messages.innerHTML="";d.messages.forEach(x=>add(x.role,x.content))}}catch(e){}}
function addChat(t){if([...chatList.children].some(x=>x.dataset.id===cid))return;const x=document.createElement("div");x.className="chat";x.dataset.id=cid;x.textContent=t.slice(0,38);chatList.prepend(x)}
async function send(text){add("user",text);const b=add("assistant","JARVIS is thinking...");b.classList.add("typing");status.textContent="● Thinking";try{const r=await fetch(API+"/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversation_id:cid,message:text,files})});const d=await r.json();if(!r.ok)throw Error(d.detail||"Server error");b.classList.remove("typing");b.textContent=d.reply;addChat(text);speak(d.reply)}catch(e){b.textContent="Error: "+e.message}finally{status.textContent="● Online"}}
form.addEventListener("submit",e=>{e.preventDefault();const t=prompt.value.trim();if(t){prompt.value="";send(t)}});prompt.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
document.getElementById("newChat").onclick=()=>{cid=crypto.randomUUID();localStorage.setItem("jarvisCid",cid);files=[];renderFiles();welcome()};
document.getElementById("clearBtn").onclick=async()=>{await fetch(API+"/history/"+cid,{method:"DELETE"});welcome()};
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("theme",document.body.classList.contains("light")?"light":"dark")};
if(localStorage.getItem("theme")==="light")document.body.classList.add("light");
document.addEventListener("click",e=>{const b=e.target.closest("[data-prompt]");if(b){prompt.value=b.dataset.prompt;form.requestSubmit()}});
fileInput.onchange=async()=>{for(const f of fileInput.files){const fd=new FormData();fd.append("file",f);const r=await fetch(API+"/upload",{method:"POST",body:fd});if(r.ok)files.push((await r.json()).name)}renderFiles();fileInput.value=""};
function renderFiles(){fileBar.innerHTML=files.map(x=>'<span class="fileTag">📄 '+x+'</span>').join("")}
let recognition=null;if("webkitSpeechRecognition"in window||"SpeechRecognition"in window){const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.continuous=false;recognition.interimResults=false;recognition.lang="en-US";recognition.onresult=e=>{prompt.value=e.results[0][0].transcript;form.requestSubmit()};recognition.onend=()=>status.textContent="● Online"}
document.getElementById("micBtn").onclick=()=>{if(!recognition)return alert("Speech recognition is not supported by this browser.");recognition.start();status.textContent="● Listening"};
document.getElementById("voiceToggle").onclick=()=>{voiceOn=!voiceOn;document.getElementById("voiceToggle").textContent=voiceOn?"🔊 Voice On":"🎤 Voice"};
function speak(text){if(!voiceOn||!("speechSynthesis"in window))return;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}
history();